plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "E:\\REACT NATIVE\\parent-teacher-app\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "E:\\REACT NATIVE\\parent-teacher-app"
command = "expo export -p web"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]